### ISSUE TITLE
Does wireplay support IPV6?.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pmcgleenon/wireplay#3]
```
 We needed a tcp replay tool to test our product for the traffic that passes through the firewall which has TCP proxy. We would like to know if the Wieplay supports IPV6 also?.
  
Thanks.
```

Original issue reported on code.google.com by `rak...@gmail.com` on 19 Jan 2012 at 3:32

**Comment by pmcgleenon** [comment]
IPv6 is supported for the socket connection between the wireplay client & server.

IPv6 is not supported in the pcap file
